language: python
python:
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements/development.txt
script:
    - pep8 .
    - python homie_server/manage.py test users posts
notifications:
    slack: hans-hq:e3X4Z2Ip23KkdW4pbhqeZ9AN
